/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.visao;

/**
 *
 * @author Jean
 */
public class TelaMenuFuncionário extends javax.swing.JFrame {
    TelaEscolherTipoDeConta telaescolhertipodeconta = new TelaEscolherTipoDeConta();
    TelaSenhaEncerramentoDeConta telasenhaencerramentodeconta = new TelaSenhaEncerramentoDeConta();
    TelaConsultarDados telaconsultardados = new TelaConsultarDados();
    TelaAlterarDados telaalterardados = new TelaAlterarDados();
    TelaSenhaAdmCadastrarFuncionario telasenhaadmcadastrarfuncionario = new TelaSenhaAdmCadastrarFuncionario();
    TelaSenhaFuncionarioRelatorio telasenhafuncionariorelatorio = new TelaSenhaFuncionarioRelatorio();

    /**
     * Creates new form TelaMenuFuncionário
     */
    public TelaMenuFuncionário() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLmenufuncionario = new javax.swing.JLabel();
        jBsair = new javax.swing.JButton();
        jBabrirconta = new javax.swing.JButton();
        jBencerrarconta = new javax.swing.JButton();
        jBconsultardados = new javax.swing.JButton();
        jBalterardados = new javax.swing.JButton();
        jBcadastrofuncionario = new javax.swing.JButton();
        jBgerarrelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco Malvader");

        jLmenufuncionario.setText("Menu Funcionário");

        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jBabrirconta.setText("Abertura de Conta");
        jBabrirconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBabrircontaActionPerformed(evt);
            }
        });

        jBencerrarconta.setText("Encerramento de Conta");
        jBencerrarconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencerrarcontaActionPerformed(evt);
            }
        });

        jBconsultardados.setText("Consultar Dados");
        jBconsultardados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultardadosActionPerformed(evt);
            }
        });

        jBalterardados.setText("Alterar Dados");
        jBalterardados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterardadosActionPerformed(evt);
            }
        });

        jBcadastrofuncionario.setText("Cadastro de Funcionários");
        jBcadastrofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrofuncionarioActionPerformed(evt);
            }
        });

        jBgerarrelatorio.setText("Gerar Relatórios");
        jBgerarrelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgerarrelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLmenufuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBsair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBabrirconta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBencerrarconta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBcadastrofuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBconsultardados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBalterardados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBgerarrelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBsair)
                .addGap(18, 18, 18)
                .addComponent(jLmenufuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBabrirconta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBencerrarconta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcadastrofuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBconsultardados)
                .addGap(4, 4, 4)
                .addComponent(jBalterardados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBgerarrelatorio)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        // TODO add your handling code here:
        TelaLoginFuncionario telaloginfuncionario = new TelaLoginFuncionario();
        telaloginfuncionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBabrircontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBabrircontaActionPerformed
        // TODO add your handling code here:
        telaescolhertipodeconta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBabrircontaActionPerformed

    private void jBencerrarcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencerrarcontaActionPerformed
        // TODO add your handling code here:
        telasenhaencerramentodeconta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBencerrarcontaActionPerformed

    private void jBconsultardadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultardadosActionPerformed
        // TODO add your handling code here:
        telaconsultardados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBconsultardadosActionPerformed

    private void jBalterardadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterardadosActionPerformed
        // TODO add your handling code here:
        telaalterardados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBalterardadosActionPerformed

    private void jBcadastrofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrofuncionarioActionPerformed
        // TODO add your handling code here:
        telasenhaadmcadastrarfuncionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBcadastrofuncionarioActionPerformed

    private void jBgerarrelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgerarrelatorioActionPerformed
        // TODO add your handling code here:
        telasenhafuncionariorelatorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBgerarrelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuFuncionário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBabrirconta;
    private javax.swing.JButton jBalterardados;
    private javax.swing.JButton jBcadastrofuncionario;
    private javax.swing.JButton jBconsultardados;
    private javax.swing.JButton jBencerrarconta;
    private javax.swing.JButton jBgerarrelatorio;
    private javax.swing.JButton jBsair;
    private javax.swing.JLabel jLmenufuncionario;
    // End of variables declaration//GEN-END:variables
}
