/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.visao;

/**
 *
 * @author Jean
 */
public class TelaMenuCliente extends javax.swing.JFrame {
    TelaSenhaClienteSaldo telasenhaclientesaldo = new TelaSenhaClienteSaldo();
    TelaDepositoMenuCliente teladepositomenucliente = new TelaDepositoMenuCliente();
    TelaSenhaClienteSaque telasenhaclientesaque = new TelaSenhaClienteSaque();
    TelaSenhaClienteExtrato telasenhaclienteextrato = new TelaSenhaClienteExtrato();
    TelaSenhaClienteConsultarLimite telasenhaclienteconsultarlimite = new TelaSenhaClienteConsultarLimite();

    /**
     * Creates new form TelaMenuFuncionário
     */
    public TelaMenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLmenucliente = new javax.swing.JLabel();
        jBsair = new javax.swing.JButton();
        jBsaldo = new javax.swing.JButton();
        jBdeposito = new javax.swing.JButton();
        jBsaque = new javax.swing.JButton();
        jBconsultarlimite = new javax.swing.JButton();
        jBextrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco Malvader");

        jLmenucliente.setText("Menu Cliente");

        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jBsaldo.setText("Saldo");
        jBsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaldoActionPerformed(evt);
            }
        });

        jBdeposito.setText("Depósito");
        jBdeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdepositoActionPerformed(evt);
            }
        });

        jBsaque.setText("Saque");
        jBsaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaqueActionPerformed(evt);
            }
        });

        jBconsultarlimite.setText("Consultar Limite");
        jBconsultarlimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarlimiteActionPerformed(evt);
            }
        });

        jBextrato.setText("Extrato");
        jBextrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBextratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBsair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBconsultarlimite, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jBextrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBsaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBdeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBsaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLmenucliente)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBsair)
                .addGap(18, 18, 18)
                .addComponent(jLmenucliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBdeposito)
                .addGap(4, 4, 4)
                .addComponent(jBsaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBextrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBconsultarlimite)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        // TODO add your handling code here:
        TelaLoginCliente telalogincliente = new TelaLoginCliente();
        telalogincliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaldoActionPerformed
        // TODO add your handling code here:
        telasenhaclientesaldo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBsaldoActionPerformed

    private void jBdepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdepositoActionPerformed
        // TODO add your handling code here:
        teladepositomenucliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBdepositoActionPerformed

    private void jBsaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaqueActionPerformed
        // TODO add your handling code here:
        telasenhaclientesaque.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBsaqueActionPerformed

    private void jBextratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBextratoActionPerformed
        // TODO add your handling code here:
        telasenhaclienteextrato.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBextratoActionPerformed

    private void jBconsultarlimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarlimiteActionPerformed
        // TODO add your handling code here:
        telasenhaclienteconsultarlimite.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBconsultarlimiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBconsultarlimite;
    private javax.swing.JButton jBdeposito;
    private javax.swing.JButton jBextrato;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsaldo;
    private javax.swing.JButton jBsaque;
    private javax.swing.JLabel jLmenucliente;
    // End of variables declaration//GEN-END:variables
}
